server:
  port: 8003
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8001
          predicates:
          - Path=/identity/**
        - id: profile_services
          uri: http://localhost:8002
          predicates:
            - Path=/profile/**
        - id: shop_services
          uri: http://localhost:8003
          predicates:
            - Path=/**



