services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shop-service'
      - 'POSTGRES_PASSWORD=htht01225923050'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5436:5432'